### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nev-r**
fix some typos and standardize the mixed formatting of env variables/dirnames/binaries/etc

### CODE REVIEW

**Comment by nev-r** [comment]
darci is varyingly formatted as darci, DARCI, and Darci and ought to be standardized (aside from references to the executable)

**Comment by mikechambers** [comment]
Thanks for the clean up. And noted about the use of "darci". The actually darci is D.A.R.C.I. but I didnt think that would work well. Thoughts on darci verses Darci verses DARCI?

**Comment by nev-r** [comment]
all caps really helps distinguish between the name of the app overall, and the directory/pm2 job. with or without periods is up to you but without sounds easier

**Comment by mikechambers** [comment]
Actually, looking at the lore, the D.A.R.C.I. AI refers to itself as "Darci". However I agree on using "DARCI" as it differentiates itself from the lore a bit, and for the reasons you mentioned.

**Pull request merged**
